# Build settings
permalink   : /blog/:title/
markdown    : kramdown
highlighter : pygments

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: web
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Gift Sonar
description: "Awesome gift ideas"
keywords: "gift, gifts, cool gifts"
url: http://www.giftsonar.com
baseurl: ""
# baseurl: ""

# google_analytics: UA-52446115-1
main_site: http://www.giftsonar.com
disqus_shortname: "fernandomoreira"

# navbar pages
navbar:
  - url: http://www.giftsonar.com
    title: Gift ideas generator
  - url: "http://www.giftsonar.com/blog"
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]